### ISSUE TITLE
The "Add..." context menu in Messages editor: two bugs

### ISSUE THREAD

**Issue by Lulle74** [eclipse-babel/plugins#27]
https://github.com/eclipse-babel/plugins/assets/29771741/82d70745-40b4-4340-9c73-c0552e89116e

Please see the attached movie for demonstration. 

_First bug_ is seen first 15 seconds of the movie: when trying to do "Add..." with an empty selection, nothing happens. 

The _second bug_ is demonstrated after that. I manage to create a new key if my selection isn't empty when running the "Add..." context menu item. In this case, I just save the file directly (without making any translation/addition to any Locale). 
By inspecting my Git Staging area, I see that **ALL** property files in the bundle are affected, with new keys added along with an empty value. This is bad, since normally we start out with an English translation (messages.properties) and want other languages to "fallback" onto the English version (until they have eventually been translated). Thus, it is crucial that these keys aren't created with empty values.

**Comment by claesrosell** [comment]
I agree that the current behavior is wrong. The key should only be added to the ROOT properties file. Other properties files should be altered upon modification of corresponding strings.

**Comment by claesrosell** [comment]
@Lulle74 There are no official builds of Babel plugins yet, but you should be able to download the latest buildt "P2 update site" from the "Actions tab"

**Comment by Lulle74** [comment]
> @Lulle74 There are no official builds of Babel plugins yet, but you should be able to download the latest buildt "P2 update site" from the "Actions tab"

Excellent, I have tried it out and this fix solves the issue!
