### ISSUE TITLE
Enabled CI with Github Actions and build artifacts.

### ISSUE THREAD

**Issue by claesrosell** [eclipse-babel/plugins#7]
We should build pull requests automatically and save artifacts to enable function testing.

**Comment by claesrosell** [comment]
Reopening this issue since I do not have permission to enable "Actions" on the repository.

**Comment by claesrosell** [comment]
@agafgfafa : Do you have permission to enable Action/workflows on the repository?

**Comment by GeraldMit** [comment]
@claesrosell we do have a jenkins instance, and as a commiter you should be able to access and create new pipeline/builds/etc.... https://ci.eclipse.org/babel/

**Comment by claesrosell** [comment]
To enable PR results/checks and result uploads I still think that we need GitHub Actions enabled for the repository. I also took a look at some other Eclipse projects that use GitHub and build with Jenkins and it seems like they use GitHub Actions as well. -I am far from an expert though.

I am a committer in Eclipse Birt as well and they are using both Jenkins and Actions but I was not part of the project when that was set up. 

Anyhow, it may be so that the enablement of Actions is an Eclipse Webmaster Team task since they are the owner of the repository.

**Comment by claesrosell** [comment]
Fixed by : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3344
